### ISSUE TITLE
not working at all on server

### ISSUE THREAD

**Issue by 95thcobra** [DuelMonster/SuperMiner#21]
### What should have happened
sohould have run like normal

### What actually happened
it did not run at all
### Version of SuperMiner
[1.11.2]-2.1.16.121
### Pastebin of relevant log files (fml-latest-client.log, fml-latest-server.log, latest.log)

java.io.IOException: The handle is invalid
	at java.io.FileInputStream.readBytes(Native Method) ~[?:1.8.0_121]
	at java.io.FileInputStream.read(Unknown Source) ~[?:1.8.0_121]
	at java.io.BufferedInputStream.read1(Unknown Source) ~[?:1.8.0_121]
	at java.io.BufferedInputStream.read(Unknown Source) ~[?:1.8.0_121]
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source) ~[?:1.8.0_121]
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source) ~[?:1.8.0_121]
	at sun.nio.cs.StreamDecoder.read(Unknown Source) ~[?:1.8.0_121]
	at java.io.InputStreamReader.read(Unknown Source) ~[?:1.8.0_121]
	at java.io.BufferedReader.fill(Unknown Source) ~[?:1.8.0_121]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_121]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_121]
	at lh$2.run(SourceFile:95) [minecraft_server.1.11.2.jar:?]

**Comment by DuelMonster** [comment]
Please try again with the latest release:  [[1.11.2]-2.4.32.306](https://minecraft.curseforge.com/projects/superminer-unified/files/2389726)

**Comment by 95thcobra** [comment]
well its atlest some what working now, i can mine shafts but nothing else seems to be working as of yet

edit( well after tinkering around everything seems to be working the way it should, so thank you for your help)

**Comment by DuelMonster** [comment]
You're welcome
